services:
  aerodrome:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AERODROME_REF: v3.4.123

    container_name: aerodrome
    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      TZ: America/Chicago

    volumes:
      - aerodrome-data:/data

    command:
      - python3
      - main.py
      - start

volumes:
  aerodrome-data: